name = "invoie-hub"
main = "src/worker.js"
compatibility_date = "2026-09-01"

[vars]
APP_NAME = "DEAL Invoice Hub"
BASE_URL = "https://invoie-hub.workers.dev"

[[d1_databases]]
binding = "DB"
database_name = "deal-invoice-hub"
database_id = "fd7169c5-43e7-422d-b817-fc170bc46e23"

[triggers]
crons = ["*/30 * * * *"]
